version: "3"
services:
  pg:
    image: postgres

  big-earl:
    image: micahlee/big-earl # or "big-earl" after building locally
    environment:
      DB_HOST_TEST: pg
      SECRET_KEY_BASE: "${BIG_EARL_KEY_BASE}"
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
    ports:
      - "80:80"
    expose:
      - "80"
    links:
    - pg:pg
    