FROM phusion/baseimage:0.9.22

RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    apt-add-repository -y ppa:brightbox/ruby-ng && \
    apt-get update -y
    
RUN apt-get install -y \
    build-essential \
    ruby2.5 ruby2.5-dev \
    postgresql-client \
    libpq-dev \
    unattended-upgrades \
    ldap-utils \
    git \
    update-notifier-common \
    nodejs \
    libcurl3 \
    vim \
    curl \
    jq \
    tzdata \
    wget \
    graphicsmagick
      
ADD install_phantomjs.sh .
RUN bash install_phantomjs.sh

RUN gem install bundler

RUN mkdir -p /src/big-earl

WORKDIR /src/big-earl

ADD Gemfile      .
ADD Gemfile.lock .

RUN bundle

RUN rm /etc/service/sshd/down

ENV PORT 3000
ENV DB_HOST_TEST pg

EXPOSE 3000